locale: "en-GB"
title_separator: "-"
name: "Tren Ma"
description: "Assistant Professor of Finance, University of Nottingham"
url: "https://trenma.github.io"
baseurl: ""
repository: "TrenMA/trenma.github.io"

breadcrumbs: false
words_per_minute: 160
future: false
read_more: "disabled"

# Site Author
author:
  name: "Tren Ma"
  avatar: "avatar2.JPG"
  bio: "Assistant Professor of Finance"
  employer: "University of Nottingham"
  email: "Tren.Ma@nottingham.ac.uk"
  googlescholar: "https://scholar.google.sk/citations?user=RfDck60AAAAJ&hl=en"
  github: "TrenMA"

# Comments
comments:
  provider: false

# Analytics
analytics:
  provider: false

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - CHANGELOG.md
  - CONTRIBUTING.md
  - Capfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README
  - README.md
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Europe/London

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
